export const API_USERlIST_REQUEST = "API_USERlIST_REQUEST";
export const API_USERlIST_SUCCESS = "API_USERlIST_SUCCESS";
export const API_USERlIST_ERROR = "API_USERlIST_FAILURE";

export const API_USERLOGIN_REQUEST = "API_USERLOGIN_REQUEST";
export const API_USERLOGIN_SUCCESS = "API_USERLOGIN_SUCCESS";
export const API_USERLOGIN_ERROR = "API_USERLOGIN_FAILURE";